name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: linting and styling
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls -la
          pip install -r ./requirements.txt

      - name: Lint Code
        run: pylint -d C0301 --fail-under=9.5 src/*.py

      - name: Style code
        run: pydocstyle src/
