name: workflow

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'sample.py'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: linting and styling
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pydocstyle

      - name: Lint Code
        run: pylint sample.py

      - name: Style code
        run: pydocstyle sample.py
