name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: linting and styling
    steps:
      - name: Lint Code
        run: pylint -d C0301 --fail-under=9.5 src/*.py

      - name: Style code
        run: pydocstyle src/
