name: workflow

before_script:
  - python --version
  - python -m venv venv
  - . venv\Scripts\activate
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pydocstyle

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: linting and styling
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: pylint -d C0301 --fail-under=9.5 src/*.py

      - name: Style code
        run: pydocstyle src/
